=== mrousavy/nitro/docs/static/nitro.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Nitro Modules Configuration",
  "type": "object",
  "required": [
    "cxxNamespace",
    "ios",
    "android",
    "autolinking"
  ],
  "properties": {
    "cxxNamespace": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "description": "Represents the C++ namespace of the module that will be generated. This can have multiple sub-namespaces, and is always relative to `margelo::nitro`."
    },
    "ios": {
      "type": "object",
      "required": [
        "iosModuleName"
      ],
      "properties": {
        "iosModuleName": {
          "type": "string",
          "minLength": 1,
          "description": "Represents the iOS module name of the module that will be generated This will be used to generate Swift bridges, as those are always namespaced within the clang module. If you are using CocoaPods, this should be the Pod name defined in the `.podspec`."
        }
      },
      "description": "Required: iOS configuration"
    },
    "android": {
      "type": "object",
      "required": [
        "androidNamespace",
        "androidCxxLibName"
      ],
      "properties": {
        "androidNamespace": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "description": "Represents the Android namespace ('package') of the module that will be generated. This can have multiple sub-namespaces, and is always relative to `com.margelo.nitro`."
        },
        "androidCxxLibName": {
          "type": "string",
          "minLength": 1,
          "description": "Represents the name of the Android C++ library (aka name in CMakeLists.txt `add_library(..)`). This will be loaded via `System.loadLibrary(...)`."
        }
      },
      "description": "Required: Android configuration"
    },
    "autolinking": {
      "type": "object",
      "description": "Configures the code that gets generated for autolinking (registering) Hybrid Object constructors.",
      "patternProperties": {
        "^.*$": {
          "type": "object",
          "oneOf": [
            {
              "required": [
                "all"
              ],
              "properties": {
                "all": {
                  "type": "object",
                  "required": [
                    "language",
                    "implementationClassName"
                  ],
                  "properties": {
                    "language": {
                      "type": "string",
                      "enum": [
                        "c++"
                      ]
                    },
                    "implementationClassName": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "not": {
                "required": [
                  "all"
                ]
              },
              "minProperties": 1,
              "properties": {
                "ios": {
                  "type": "object",
                  "required": [
                    "language",
                    "implementationClassName"
                  ],
                  "properties": {
                    "language": {
                      "type": "string",
                      "enum": [
                        "c++",
                        "swift"
                      ]
                    },
                    "implementationClassName": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                },
                "android": {
                  "type": "object",
                  "required": [
                    "language",
                    "implementationClassName"
                  ],
                  "properties": {
                    "language": {
                      "type": "string",
                      "enum": [
                        "c++",
                        "kotlin"
                      ]
                    },
                    "implementationClassName": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                }
              },
              "patternProperties": {
                "^(?!all$|ios$|android$).+$": {
                  "type": "object",
                  "required": [
                    "language",
                    "implementationClassName"
                  ],
                  "properties": {
                    "language": {
                      "type": "string",
                      "enum": [
                        "c++",
                        "swift",
                        "kotlin"
                      ]
                    },
                    "implementationClassName": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                }
              },
              "additionalProperties": false
            }
          ]
        }
      }
    },
    "ignorePaths": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "A list of paths relative to the project directory that should be ignored by nitrogen. Nitrogen will not look for `.nitro.ts` files in these directories."
    },
    "gitAttributesGeneratedFlag": {
      "type": "boolean",
      "default": true,
      "description": "Configures whether all nitro-generated files should be marked as `linguist-generated` for GitHub. This excludes generated files from diffing and language statistics."
    }
  }
}

=== mrousavy/nitro/external/nitro.json
{
  "$schema": "https://nitro.margelo.com/nitro.schema.json",
  "cxxNamespace": [
    "image"
  ],
  "ios": {
    "iosModuleName": "NitroImage"
  },
  "android": {
    "androidNamespace": [
      "image"
    ],
    "androidCxxLibName": "NitroImage"
  },
  "autolinking": { },
  "ignorePaths": [
    "**/node_modules"
  ],
  "gitAttributesGeneratedFlag": false
}

=== mrousavy/nitro/packages/react-native-nitro-test/nitro.json
{
  "$schema": "https://nitro.margelo.com/nitro.schema.json",
  "cxxNamespace": ["test"],
  "ios": {
    "iosModuleName": "NitroTest"
  },
  "android": {
    "androidNamespace": ["test"],
    "androidCxxLibName": "NitroTest"
  },
  "autolinking": {
    "TestObjectCpp": {
      "all": {
        "language": "c++",
        "implementationClassName": "HybridTestObjectCpp"
      }
    },
    "TestObjectSwiftKotlin": {
      "ios": {
        "language": "swift",
        "implementationClassName": "HybridTestObjectSwift"
      },
      "android": {
        "language": "kotlin",
        "implementationClassName": "HybridTestObjectKotlin"
      }
    },
    "Base": {
      "ios": {
        "language": "swift",
        "implementationClassName": "HybridBase"
      },
      "android": {
        "language": "kotlin",
        "implementationClassName": "HybridBase"
      }
    },
    "Child": {
      "ios": {
        "language": "swift",
        "implementationClassName": "HybridChild"
      },
      "android": {
        "language": "kotlin",
        "implementationClassName": "HybridChild"
      }
    },
    "PlatformObject": {
      "ios": {
        "language": "swift",
        "implementationClassName": "HybridPlatformObject"
      },
      "android": {
        "language": "kotlin",
        "implementationClassName": "HybridPlatformObject"
      }
    },
    "TestView": {
      "ios": {
        "language": "swift",
        "implementationClassName": "HybridTestView"
      },
      "android": {
        "language": "kotlin",
        "implementationClassName": "HybridTestView"
      }
    },
    "RecyclableTestView": {
      "ios": {
        "language": "swift",
        "implementationClassName": "HybridRecyclableTestView"
      },
      "android": {
        "language": "kotlin",
        "implementationClassName": "HybridRecyclableTestView"
      }
    },
    "Issue1439": {
      "ios": {
        "language": "swift",
        "implementationClassName": "HybridIssue1439"
      },
      "android": {
        "language": "kotlin",
        "implementationClassName": "HybridIssue1439"
      }
    }
  },
  "ignorePaths": [
    "**/node_modules"
  ],
  "gitAttributesGeneratedFlag": false
}
